CREATE TABLE COMMENTS (
    CommentId INTEGER PRIMARY KEY AUTOINCREMENT,
    Body TEXT NOT NULL,
    CreatedAt BIGINT NOT NULL,
    ImageURL TEXT,
    PostId INTEGER NOT NULL,
    UpdatedAt BIGINT NOT NULL,
    UserId INTEGER NOT NULL
);