CREATE TABLE EVENTS (
    EventId INTEGER PRIMARY KEY AUTOINCREMENT,
    CreatedAt BIGINT NOT NULL,
    DateTime BIGINT NOT NULL, 
    Description TEXT NOT NULL, 
    GroupId INTEGER NOT NULL,
    Title TEXT NOT NULL,
    UpdatedAt BIGINT NOT NULL,
    UserId INTEGER NOT NULL
);