CREATE TABLE EVENT_USERS (
EventUserId INTEGER PRIMARY KEY AUTOINCREMENT,
CreatedAt BIGINT NOT NULL,
EventId INTEGER NOT NULL, 
UpdatedAt BIGINT NOT NULL,
UserId INTEGER NOT NULL,
FOREIGN KEY (UserId) REFERENCES USERS(UserId)
);