CREATE TABLE GROUP (
    GroupID INTEGER PRIMARY KEY AUTOINCREMENT,
    CreatedAt BIGINT NOT NULL,
    CreatorID INTEGER NOT NULL,
    Description TEXT NOT NULL,
    Title TEXT NOT NULL,
    UpdatedAt BIGINT NOT NULL
);