CREATE TABLE POSTS (
    PostId INTEGER PRIMARY KEY AUTOINCREMENT,
    Body TEXT NOT NULL,
    CreatedAt BIGINT NOT NULL,
    GroupId INTEGER,
    ImageURL TEXT,
    UpdatedAt BIGINT NOT NULL,
    UserId INTEGER NOT NULL
);