CREATE TABLE POSTS (
    PostID INTEGER PRIMARY KEY AUTOINCREMENT,
    Body TEXT NOT NULL,
    CreatedAt BIGINT NOT NULL,
    GroupID INTEGER,
    ImageURL TEXT,
    UpdatedAt BIGINT NOT NULL,
    UserID INTEGER NOT NULL
);