CREATE TABLE IF NOT EXISTS POSTS (
    PostId INTEGER PRIMARY KEY AUTOINCREMENT,
    Body TEXT NOT NULL,
    CreatedAt BIGINT NOT NULL,
    GroupId INTEGER NOT NULL DEFAULT 0,
    ImageURL TEXT,
    Privacy TEXT,
    UpdatedAt BIGINT NOT NULL,
    UserId INTEGER NOT NULL,
    FOREIGN KEY (GroupId) REFERENCES GROUPS(GroupId),
    FOREIGN KEY (UserId) REFERENCES USERS(UserId)
);