CREATE TABLE IF NOT EXISTS EVENT_USERS (
EventUserId INTEGER PRIMARY KEY AUTOINCREMENT,
CreatedAt BIGINT NOT NULL,
EventId INTEGER NOT NULL, 
IsGoing BIT NOT NULL, 
UpdatedAt BIGINT NOT NULL,
UserId INTEGER NOT NULL,
FOREIGN KEY (EventId) REFERENCES EVENTS(EventId),
FOREIGN KEY (UserId) REFERENCES USERS(UserId)
);