CREATE TABLE COMMENTS (
CommentID INTEGER PRIMARY KEY AUTOINCREMENT,
Body TEXT NOT NULL,
CreatedAt BIGINT NOT NULL,
ImageURL TEXT,
PostID INTEGER NOT NULL,
UpdatedAt BIGINT NOT NULL,
UserID INTEGER NOT NULL
);