CREATE TABLE IF NOT EXISTS USER_USERS (
UserUserId INTEGER PRIMARY KEY AUTOINCREMENT,
CreatedAt BIGINT NOT NULL,
FollowerId INTEGER NOT NULL,
SubjectId INTEGER NOT NULL,
UpdatedAt BIGINT NOT NULL,
FOREIGN KEY (FollowerId) REFERENCES USERS(UserId),
FOREIGN KEY (SubjectId) REFERENCES USERS(UserId)
);